version: '3.4'
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - .:/app/
      - node_modules:/app/node_modules
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env

volumes:
  node_modules:
